#!/usr/bin/python3
"""
Module factors
This module factorizes a number to try to decrypt it.
Functions:
    def main()
"""
import math
import sys


def main():
    """Factorizes a number from a file provided as a command-line argument"""
    if len(sys.argv) != 2:
        print("Usage: .factors <file>")
        sys.exit(1)

    try:
        file_name = sys.argv[1]
        with open(file_name, "r") as file:
            for i in file:
                num = int(i.strip())  # Remove newline characters
                sqrtt = math.isqrt(num)  # Directly compute integer square root

                for j in range(2, sqrtt + 1):
                    if num % j == 0:
                        k = num // j  # Use integer division
                        print(f"{num}={j}*{k}")  # Print in the correct format
                        break
    except FileNotFoundError:
        print("The file was not found.")
    except Exception as err:
        print(f"Exception: {err}")

if __name__ == "__main__":
    main()
